### ISSUE TITLE
Looking for "name conversion"

### ISSUE THREAD

**Issue by vylmen** [jacksonllee/pycantonese#20]
Hello,

please excuse any ignorance on the topic of romanization of Cantonese, as I neither know the language nor it's pronunciation rules. My use case is merely transliterating actor and role names for movie and drama series purposes.

I've tried several packages, but I keep seeing the same differences. For these romanizations, tones are not used, but this is minor. Right now I have only one example at hand, because I don't use it often and forgot about the earlier cases, but I will try to find more if this is not a "structural" problem, but specific to the character.

The example is [Bruce Leung / Leung Siu Lung](https://zh.wikipedia.org/wiki/%E6%A2%81%E5%B0%8F%E9%BE%8D) which comes up as:

```python
In [4]: pc.characters2jyutping('梁小龍')
Out[4]: ['loeng4', 'siu2', 'lung4']
```

The loeng4 versus leung puzzles me and I can also not find any sources / documentation that could explain the difference to me, because basically I don't know what to search for :) As a speaker of Dutch, English and German, in none of the languages I would pronounce *loeng* or *leung* the same.

Are these name conversions based on different rules or even a different system entirely?

**Comment by jacksonllee** [comment]
Hello @vylmen, there are indeed multiple romanization schemes going on here. For the surname 梁, both "loeng4" and "Leung" are intended to denote the same pronunciation for Hong Kong Cantonese.

* "loeng4" comes from the standardized [Jyutping](https://www.lshk.org/jyutping) romanization scheme. It was proposed by academic linguists in Hong Kong in the 1990's, and has been gaining popularity steadily since then.

* "Leung" comes from a romanization system that has been around for over a century, that first came into being during the British colonial era of Hong Kong out of necessity (for representing in English place and person names as pronounced in Hong Kong Cantonese; [here](https://en.wikipedia.org/wiki/Hong_Kong_Government_Cantonese_Romanisation) is a relevant Wikipedia article). The system (if we could call it as such) is not entirely standardized, as multiple spellings have been used for the same Cantonese pronunciation of the same Chinese character. (For 梁, I've seen Leung and Leong, while my own surname 李 can be either Lee or Li.) Here is a [list of surnames and their different romanized forms](https://en.wikipedia.org/wiki/List_of_common_Chinese_surnames) from Wikipedia.

For the purpose of transliterating actor and actress names, if you want accurate results (in the sense of matching what the respective actor/actress actually uses in real life), then your best bet is probably to do some lookup through Wikipedia (like you did for the actor 梁小龍) due to the unpredictable nature of such romanization; programmatically, I imagine it's possible to grab a Wikipedia page's HTML and target the appropriate tags and attributes to retrieve the romanized name.

If scraping Wikipedia is not a good option for you -- Based on your description, am I right in thinking you'd want something intuitive and accessible for non-linguists (i.e., you'd not want something technical like the IPA)? I could see how the Jyutping system might be confusing (things like "z", "c", "j", etc. in Jyutping are not what one would expect from an English pronunciation perspective). Anecdotally, native speakers of English attempting to learn Cantonese have found the [Yale](https://en.wikipedia.org/wiki/Yale_romanization_of_Cantonese) romanization system more English-friendly.  If you'd like to give it a shot, PyCantonese has a [jyutping2yale](http://pycantonese.org/jyutping.html#jyutping-to-yale-conversion) function.

Please let me know if you need more information!

**Comment by vylmen** [comment]
Thank you very much for the detailed explanation.

It's sort of what I was expecting. As with Korean, there have been multiple systems and people born in the era of the older system, use that system as changing their name both looks different and is expensive (passports, birth certificates, etc). And it certainly doesn't help if the system is not consistent itself.

What I want to use it for is to prevent that duplication. Pages are created with romanized URLs and titles to aid non-native speakers in finding the page. Sometimes, a person exists under his/her Cantonese name, but featured in a Mandarin title and duplicate pages are created. This is compounded by the fact that some are stored as their English name with either Cantonese or Mandarin surname. Additionally if a person plays in both languages (dubbed or not), it's convenient to have both romanizations listed.

And as for the character they play - I would use transliteration here too, if the series/movie is in Cantonese (not currently my personal focus, but that can change). For character names it would seem logical to use Jyutping, but I'll do more research given the sources you quoted on what is sensible. Once again, thanks for the valuable input!

**Comment by jacksonllee** [comment]
You're welcome! I'm closing this issue for now. If you have more specific questions later, please feel free to open new issues.
