### ISSUE TITLE
Can't distinguish high falling tone from high level tone

### ISSUE THREAD

**Issue by LawranceFung** [jacksonllee/pycantonese#23]
Officially, Yale romanization should distinguish high level tone ā from high falling tone à (jyutping doesn't).  Would it be possible to make pycantonese do that?

**Comment by jacksonllee** [comment]
Hello, as of pycantonese v3.0.0, the only spot where Yale romanization appears in pycantonese is the [jyutping_to_yale](https://pycantonese.org/generated/pycantonese.jyutping_to_yale.html) function. Since (as you've pointed out) jyutping itself doesn't distinguish high-level tone and high-falling tone, the `jyutping_to_yale` function cannot make this distinction.

Let me know if you have other questions!
